FROM postgres:16-alpine

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=mrccut

# Expose PostgreSQL port
EXPOSE 5432

# Add initialization scripts
COPY init.sql /docker-entrypoint-initdb.d/
