FROM postgres:16-alpine

# Set environment variables
ENV POSTGRES_USER=default
ENV POSTGRES_PASSWORD=npg_8eruKvscO9dB
ENV POSTGRES_DB=neondb

# Expose PostgreSQL port
EXPOSE 5432

# Add initialization scripts
COPY init.sql /docker-entrypoint-initdb.d/
